### ISSUE TITLE
Needs to be updated

### ISSUE THREAD

**Issue by AbuMaia** [mkopta/toggle-touchscreen#1]
This extension worked well, while it worked. Gnome Shell has since been updated; I run 3.16.4, and there's a review on the extension page asking for an update to 3.18. Could you fix this soon, please?

**Comment by mkopta** [comment]
Thanks for reporting this issue. I will look into it during the weekend and will try to fix it.

**Comment by mkopta** [comment]
Alright, with a bit of delay (sorry about that) I just released version 1.2, that should be compatible with gnome-shell 3.16 and 3.18. Hope that resolves this issue. If not, feel free to reopen. Thank you very much for reporting this!

**Comment by AbuMaia** [comment]
Well, here we are again. Time for another update. :)

**Comment by mkopta** [comment]
Hi, I just updated the metadata, created new release and published it on gnome extensions site. Sorry it took so long. Next time please file a new issue :-) Thanks for reporting though!

**Comment by mkopta** [comment]
BTW, since I don't use this extensions myself anymore, I didn't test the compatibility, so if it doesn't work as it should, please file new issue.
