### ISSUE TITLE
Support Gnome 3.26 (Ubuntu 17.10) and Wayland

### ISSUE THREAD

**Issue by lelecanfora** [mkopta/toggle-touchscreen#2]

**Comment by mkopta** [comment]
Will try to look into this this week. I don't have Ubuntu 17.10 on me right now, but I will try something.

**Comment by mkopta** [comment]
Sorry for such a delay. Better late than never I guess [1]. I wrote a comment on the extension page [0] about Wayland support.

Please, try out the new version and feel free to report back if it doesn't work for you.

[0] https://extensions.gnome.org/extension/991/toggle-touchscreen/
[1] https://github.com/mkopta/toggle-touchscreen/releases/tag/v1.4
